### ISSUE TITLE
CRSF device names longer than 12 characters break the device page

### ISSUE THREAD

**Issue by howels** [DeviationTX/deviation#1017]
When using CRSF module protocol, if a device name is > 12 characters then a blank line is shown and the CRSF device page cannot be used.

I've tried to fix it myself but I cannot figure out where the 12 char limit is coming from and my attempts to pre-emptively cut the name strings short before they hit whatever is throwing the error are going nowhere. 

So I'm leaving this issue here in case someone who knows more about the GUI rendering process finds it.

**Comment by hexfet** [comment]
What transmitter are you using?
What radio module are you using?
Can you please give an example of a device name that causes the failure?

I only have a Crossfire radio and it doesn't seem to have this problem.  The device name is "XF Transmitter" which is 14 characters and works correctly.

You can try reducing the constant CRSF_MAX_NAME_LEN to see if the behavior changes.

**Comment by howels** [comment]
This happens with ExpressLRS devices. We can for instance see the RX which has a shorter name but the TX is not visible with the default name "BetaFPV Micro TX"
I experimented a lot trying to shorten the length of strings but nothing seemed to work, Deviation would show a blank line when the input string was too long - it would be strongly desirable to truncate the string instead of showing a blank line.

**Comment by howels** [comment]
FYI I have tried a custom build with CRSF_MAX_NAME_LEN increased to 40 characters and the 14 character limit still applies.

**Comment by hexfet** [comment]
Thanks for the pointer in the right direction.  Should be fixed by #1020.  Please give it a try.

**Comment by howels** [comment]
> Thanks for the pointer in the right direction. Should be fixed by #1020. Please give it a try.

Thanks, I'll give it a go tomorrow. Really appreciate you looking at this!

**Comment by howels** [comment]
BTW this is now fixed as of https://github.com/DeviationTX/deviation/commit/458a87e71dbaf7379d0bd94a44bc62243c6da258
