### ISSUE TITLE
Load model and change icon, DEVO10 will restart

### ISSUE THREAD

**Issue by huaitao** [DeviationTX/deviation#282]
Load model and change icon, DEVO10 will restart.(The modelico folder contains 87 icons)
Edition:debug-devo10-v5.0.0-d9cd81f

**Comment by vladislavy** [comment]
Will it work normally if you decrease number of icons? What time it takes to open the list of icons? From pressing the button to displaying the list.

**Comment by huaitao** [comment]
When decrease number of icons it work normally.If do not decrease number of icons,it takes about 2 seconds.(Some mode can change icon and not restart)

**Comment by vladislavy** [comment]
OK, it looks like I know the reason.

**Comment by vladislavy** [comment]
Can you test the build with fix?
https://www.deviationtx.com/forum/builds/7261-load-model-and-change-icon-devo10-will-restart

**Comment by huaitao** [comment]
OK,I'll test tonight.

**Comment by huaitao** [comment]
Sorry,I tried, but it didn't work，but I downloaded the latest version and found no this problem(deviation-devo10-v5.0.0-9c46f3b).I think it was caused by the wrong modelx.ini configuration file.Sorry,I should have tested and asked questions.Thank you for what you've done.
