### ISSUE TITLE
FrskyX Timing

### ISSUE THREAD

**Issue by Wene001** [DeviationTX/deviation#311]
i get very sporadic telemetry with FrskyX in LBT EU mode.
First i had the same problems with multimodule, but (thx to) MikeBlandford got it fixed.
https://www.rcgroups.com/forums/showpost.php?p=38484818&postcount=10107

Could these be tested and implemented in Deviation, please
Cheers Wene

**Comment by goebish** [comment]
Please check this build and report:
https://www.dropbox.com/sh/h1ait0i6kwgf6q3/AACKUCvch2TdpJRHGC1MAb3Ca?dl=0

**Comment by Wene001** [comment]
Thanks, but i cant test 7e or 10 Builds
My Hardware is Devo6s, Devo12s and DevoF7_XMS

I'll test this 
https://www.deviationtx.com/forum/protocol-development/5356-new-frskyx-protocol?start=880#65760
if i had free time

**Comment by goebish** [comment]
Ah ok, I had not noticed hexfet has already fixed it.

**Comment by Wene001** [comment]
Made a short workbench test with a X6R in LBT Mode.
Link quality an telemetry stability looks fine now.

**Comment by TheRealMoeder** [comment]
Fixed in #323
