### ISSUE TITLE
Main page text

### ISSUE THREAD

**Issue by Chen-Leon** [DeviationTX/deviation#330]
Build version is 711ada2
download the dfu on deviation web site
Tx Type is Devo10
Can tried reproducing this on the emulator

![default](https://user-images.githubusercontent.com/18112348/33917698-b3a94be4-dfea-11e7-9784-9bf8053ea0c0.jpg)

**Comment by vladislavy** [comment]
I think it related to "Modifying 04b03 font to have hungarian characters"
https://github.com/DeviationTX/deviation/commit/49dfbca2711a6f8d3754abe2257a0cd9c3df18c
Before it all looks fine.

**Comment by F-D-R** [comment]
Strange, I didn't change anything about alignment, just added a few characters, and it worked well in the 12E emulator and I think I tried it in the TX  as well, but I have to check that...

**Comment by vladislavy** [comment]
I just change 04b03 font at emulator to old version and the alignment changed. It'a a miracle! I don't understand how it possible.

**Comment by F-D-R** [comment]
I guess FontForge does some changes in the background.
I'm quite unhappy with it anyway, because I could ruin the font by simple edit commands, like copy/paste/cut/undo etc, so in the end I had to be very careful with changes to get a working font...

**Comment by F-D-R** [comment]
BTW how you can use this font for Russian? There are no Russian characters in it, but it is used for translated text on the trim page...

**Comment by vladislavy** [comment]
I don't use Russian with transmitters at all.

**Comment by vladislavy** [comment]
I think it related to some problem with alignment at "bdf_to_font.pl"

Before we havn't any symbol with 6 pixel height without descent in charset.

**Comment by vladislavy** [comment]
Just now tested it. I manually added 1 pixel at top to exclamation mark (BBX 1 6 0 0) with old 04b03.bdf and get the same result.

**Comment by F-D-R** [comment]
I see.
What to do? Those characters need those pixels. I even had to lower all the capital letters to make some room...

**Comment by vladislavy** [comment]
Nothing. Apply the fix and forget about it. I think it will never change in the future, now all pixel places (8 pixel height) are used. But takes in mind that it can happen with new additional fonts.
