### ISSUE TITLE
how to edit bmp file?

### ISSUE THREAD

**Issue by zhxzsh** [DeviationTX/deviation#337]
in folder deviation/src/fs/320x240x16/media/ have many *.bmp files,I use photoshop edit the picture files,and save as 16bit bmp format file,but the file cannot be build with Docker,which picture tool can edit the bmp format picture file?

**Comment by F-D-R** [comment]
https://www.deviationtx.com/forum/model-icons/875-instructions-for-making-model-icons

**Comment by OpenUAS** [comment]
Close issue?
