### ISSUE TITLE
Commit e50fce3 - "Add ability to specify display scale/format string" doesn't work for virtual channels

### ISSUE THREAD

**Issue by vladislavy** [DeviationTX/deviation#340]
https://www.deviationtx.com/forum/builds/7571-strange-behavior-of-devo-10

**Comment by vladislavy** [comment]
I think that virtual channels havn't limits, so it will not work for virtual channels. Probably will be better to revert this commit.
https://github.com/DeviationTX/deviation/pull/328/files

**Comment by nknotts** [comment]
#328

**Comment by OpenUAS** [comment]
@vladislavy Did it work for you?

**Comment by vladislavy** [comment]
Yes.

**Comment by F-D-R** [comment]
Can it be closed?

**Comment by vladislavy** [comment]
Yes.
