### ISSUE TITLE
irangex irx-ir8m missing A7105

### ISSUE THREAD

**Issue by JLo66** [DeviationTX/deviation#353]
I just update the firmware to 2018-01-31 and now get this error on startup.  

"Missing modules: A7105 ..."

Is there a way to fix it?

Any help much appreciated,
Jeff.

**Comment by vladislavy** [comment]
Most likely it is filesystem problem. Try to format transmitter USB drive, copy filesystem and use "Safely Remove Hardware".

**Comment by dickkyhenriette** [comment]
i have the same problem slow formatted the drive still the same problem .
its all over the internet many of us users don't even  try to upgrade .
i down graded it to stock firmware and its working normal again.
Sad to see this love this radio.
