### ISSUE TITLE
www.deviationtx.com down

### ISSUE THREAD

**Issue by TheRealMoeder** [DeviationTX/deviation#401]
It gives a 503 when trying to open the site.

**Comment by F-D-R** [comment]
I've already tried to contact PB...

**Comment by PhracturedBlue** [comment]
I am aware and have filed a ticket to the host about it.

**Comment by PhracturedBlue** [comment]
Apparently there is an issue with the PHP version we were using on the hosting provider.  I updated to a later version, and everything appears to be working again.  Please let me know if you see any issues

**Comment by F-D-R** [comment]
The Wiki pages still give some warnings:
https://www.deviationtx.com/wiki/supported_models

**Comment by PhracturedBlue** [comment]
I fixed it now.  I noticed that there is no 'login' link on the wiki (if you aren't logged in).  Do you know if it was ever there?  I thought there was a 'login' link on the wiki.

**Comment by PhracturedBlue** [comment]
It looks like there were some API changes in the latest Wiki code.  I've already fixed a couple of issues, but if you see any PJHP errors on the Wiki, please let me know.

**Comment by F-D-R** [comment]
Thanks!

**Comment by F-D-R** [comment]
That's because the Wiki isn't within Joomla, only was made to look similar, and only the main menu was ported, so the other plugins and modules, like the login don't work...

**Comment by TheRealMoeder** [comment]
I don't know if it is related, but I have problems uploading test builds using the provided perl script...can anyone check?

**Comment by PhracturedBlue** [comment]
Yep...the new PHP caught a bug in the uploader script.  Please verify it is wokring now

**Comment by TheRealMoeder** [comment]
Works as a treat, once again thanks for the quick fix!

**Comment by captainju** [comment]
I don't know if it is related, but some model icons doesn't show up in the forum https://www.deviationtx.com/forum/model-icons
For example here:
https://www.deviationtx.com/forum/bw-icons-for-devo-7e-10/7907-velocidrone-icon-for-7e-10-12e

**Comment by rebel008** [comment]
it appears the site is down again as of today(30 jul 2019) any one know anything or able to help?
when trying to goto the site i get; Error: Call to undefined function Joomla\Registry\Format\json_decode(): Call to undefined function Joomla\Registry\Format\json_decode()

**Comment by TheRealMoeder** [comment]
@PhracturedBlue @F-D-R can you have a look?

**Comment by PhracturedBlue** [comment]
I'll take a look

**Comment by PhracturedBlue** [comment]
Apparently the php installation was changed by the hosting provider, though I don't know why.  Switched to newer PHP version, and everything works again

**Comment by TheRealMoeder** [comment]
Thanks. Forum is still not working

**Comment by PhracturedBlue** [comment]
very odd.  I did something and it seems ok now.  I have no idea what happened there

**Comment by rebel008** [comment]
you guys are absolutely amazing! big thanks!!!
