### ISSUE TITLE
Flysky LQI telemetry on CH14

### ISSUE THREAD

**Issue by Tygrys-1** [DeviationTX/deviation#422]
Flysky AFHDS2A protocol has max 14 channels. The telemetry "LQI output" setting allows to select only up to 12 channel. Can it be expanded to 14?

**Comment by goebish** [comment]
Yes, expect it in the next nightly.

**Comment by Tygrys-1** [comment]
Wow, what a speed!

**Comment by goebish** [comment]
Closing issue ;)
