### ISSUE TITLE
T8SG V2 Plus - voice volume on turn-on

### ISSUE THREAD

**Issue by tigger1955** [DeviationTX/deviation#449]
Using dfplayer and setting the voice volume, the system ignores the volume setting intermittently on turn on and boots with the welcome message at full volume.  after boot the voice commands following are at the correct volume.

**Comment by TheRealMoeder** [comment]
We will have to live with this, as there is some delay before dfplayer is ready to receive commands on startup, but we don't want to delay the boot up process just for volume settings...
