### ISSUE TITLE
T8SG V2 datalog signature

### ISSUE THREAD

**Issue by Tygrys-1** [DeviationTX/deviation#452]
Currently it is the same as the Devo 7e, (0x7e) which is wrong, as the Devo 7e has different datalog entries for buttons and no aux channels. It should be changed to whatever unique for T8SG V2.

**Comment by Tygrys-1** [comment]
It will also help to know the telemetry type (Spectrum, Walkera or FrSky) as the datalog file can have different models logged and there is no way to tell the meaning(headers) of the data fields when without this information. 
As there are only few radio type identifiers used, maybe this information can be added to the radio-type data byte, to not change the log structure.

**Comment by howard0su** [comment]
All t8 serial changes to 0x18 as this
