### ISSUE TITLE
T8SG V2 startup screen.

### ISSUE THREAD

**Issue by phaseIV** [DeviationTX/deviation#458]
I’ve installed the latest (nightly) firmware on my T8SG v2 controller and evertything is working super fine! Many thanks for that. There’s just one issue that I’d like to report here; each time I turn on the T8SG there is a popup showing “Ch3 is -6%, safe value = -100”. This message is blocking the controllers operation, I have to press enter to get rid of the popup before the controller starts working.

Is this intentional? Or can I change the configuration so that the controller starts working immediately without the popup? Hope you can help me. Many thanks.

**Comment by TheRealMoeder** [comment]
It is intentional, please read this chapter in the manual:
https://www.deviationtx.com/manuals/html-devo10-en/ch_mainpage.html#safety-system

**Comment by phaseIV** [comment]
Completely missed that. Thanks for the info.
