### ISSUE TITLE
[TODO] Cleanup Music API usage in protocols

### ISSUE THREAD

**Issue by howard0su** [DeviationTX/deviation#495]
There are couple of protocols are using MUSIC APIs. this is not right behavior as protocol should not impact the user experience. Someone need analyze the needs for protocols and expose some APIs from PROTOCOL apis for those protocols to consume.

I believe most of MUSIC API calls are not needed as most of them are play music of Done_Binding which should be played by the logic inside protocol.c.

$git grep MUSIC protocol
protocol/bayang_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);    // Shouldn't play telemetry alarm doing bind init
protocol/bayang_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/bugs3_a7105.c:        MUSIC_Play(MUSIC_ALARM1);
protocol/cflie_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/cg023_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);     // Shouldn't play telemetry alarm doing bind init
protocol/cg023_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/cx10_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);      // Shouldn't play telemetry alarm doing bind init
protocol/cx10_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/esky150_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/esky_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);      // Shouldn't play telemetry alarm doing bind init
protocol/esky_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/fy326_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);     // Shouldn't play telemetry alarm doing bind init
protocol/fy326_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/fy326_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);     // Shouldn't play telemetry alarm doing bind init
protocol/fy326_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/h8_3d_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);     // Shouldn't play telemetry alarm doing bind init
protocol/h8_3d_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/hontai_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);    // Shouldn't play telemetry alarm doing bind init
protocol/hontai_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/inav_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/kn_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/mjxq_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);      // Shouldn't play telemetry alarm doing bind init
protocol/mjxq_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/mt99xx_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);    // Shouldn't play telemetry alarm doing bind init
protocol/mt99xx_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/protocol.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/q303_nrf24l01.c:        MUSIC_Beep("d2", 100, 100, (vtx_channel & 7) + 1);
protocol/symax_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/v202_nrf24l01.c:        // MUSIC_Play(MUSIC_TELEMALARM1);      // Shouldn't play telemetry alarm doing bind init
protocol/v202_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);
protocol/yd717_nrf24l01.c:            MUSIC_Play(MUSIC_DONE_BINDING);

**Comment by howard0su** [comment]
@goebish maybe we can discuss what protocols really need audio functions.

**Comment by goebish** [comment]
Only Q303 really need it, all the rest can be removed.

**Comment by TheRealMoeder** [comment]
100% agree

**Comment by goebish** [comment]
This is to indicate the current VTX channel (1-8).

**Comment by howard0su** [comment]
> This is to indicate the current VTX channel (1-8).

So the original Tx is use audio to indicate that? Can we telemetry to display it in a different way?

Sorry i don't play drone but only fixed wing. So I have no idea how it works and why we need it.

**Comment by TheRealMoeder** [comment]
@goebish please add manual entry for Q303 to explain the beeps

**Comment by goebish** [comment]
Ok, it's only used for the CX35 sub-format actually.

**Comment by TheRealMoeder** [comment]
Great thanks. If time permits, the following protocols are also missing manual entries:
`MT99XX, ASSAN, FQ777, iNAV, GW008, DM002` :-)

**Comment by goebish** [comment]
Ok, that's on my todo list

**Comment by TheRealMoeder** [comment]
Don't put it up to high on the list, I'm sure there's more important stuff to do ;)

**Comment by goebish** [comment]
Also, they are only undocumented protocols, but there are also many more undocumented sub-formats :(
I think we should keep a link to this spreadsheet on deviationtx.com frontpage and/or in the manual, I keep it updated:
http://bit.ly/deviation_models
