### ISSUE TITLE
Help Needed to test Tx with test builds

### ISSUE THREAD

**Issue by howard0su** [DeviationTX/deviation#553]
I want to collect who have which Tx can help test certain changes:

- [x] at9 -- ()
- [x] devo10 -- ()
- [x] devo12 -- ()
-  devo12e -- (almost identical with devo10)
- [ ] devo6 -- ()
- [x] devo7e -- (howard0su)
- [x] devo7e-256 -- ()
- [x] devo8 -- ()
- [x] devof12e -- (howard0su)
- [ ] devof4 -- ()
- [x] devof7 -- ()
- [x] t8sg

**Comment by goebish** [comment]
devo10 + t8sg + t8sg v2 plus

**Comment by TheRealMoeder** [comment]
devo7e, t8sg, t8sg v2+

**Comment by PhracturedBlue** [comment]
at9, devo10, devo12, devo8, devo7e (w and w/out 256) devof12e, devof7 (t8sg, t8sg v2 plus, x9d)

But I'm not flying these days, so am limited only to what I can test on the ground.

**Comment by howard0su** [comment]
please help verify new compiler and new libopencm3. I got report that combined both change cause infinit restart on devo12. I would like to know the crash so that I can fix.

**Comment by howard0su** [comment]
What is the status of x9d? As today the build is broken.

**Comment by PhracturedBlue** [comment]
x9d build was never finished because there was no way to support multiple protocols at the time.  That has changed since with the 4-in-1 module I think, so maybe it is worth a re-look.  It is a pretty difficult port as the hardware is very different.  I'm not sure if we'd win over many users given it has a good open-source firmware already

**Comment by TheRealMoeder** [comment]
12e shouldn't matter, as it is basically a 10 with two additional knobs

**Comment by hexfet** [comment]
devo10, t8sg, t8sg v2 plus

**Comment by howard0su** [comment]
Looks like we have reasonable coverage for almost every Tx. Can I request that we can have bi-weekly test activity to test various branch to make sure we can have enough tests for some changes.

The things in my mind is:
compiler change #480 
linker script change #550

**Comment by caixiaohai0** [comment]
d8s,d12s,d10,d7e（256）
