### ISSUE TITLE
GPS Telemetry data is incorrect

### ISSUE THREAD

**Issue by howard0su** [DeviationTX/deviation#627]
here is the user reported issue: 
https://www.deviationtx.com/forum/6-general-discussions/8209-problems-with-devo-f12e-nightly-builds#72446

The issue is reported by F12E. I looked at the code. Looks like GPS coord and GPS time are both handled in the generic way.

**Comment by howard0su** [comment]
@vladislavy please help

**Comment by vladislavy** [comment]
GPS data is correct, I tested it with Walkera GPS and telemetry module. It looks like QR-X350 Pro GPS sensor use format DD.DDDDD, not DD MM.MM.

**Comment by vladislavy** [comment]
I'm afraid that QR-X350 Pro GPS sensor has its own data format, which will be specific to QR-X350 only.
