### ISSUE TITLE
Handling Japanese translation

### ISSUE THREAD

**Issue by PhracturedBlue** [DeviationTX/deviation#632]
We have a japanese translation now, thanks to transifex and Toshihiro Makuuchi.  However, we don't have a check to verify that all necessary characters in the language files are available in our font files, and the translation is mostly unusable today (from how many strings are blank in the emulator...i can't read Japanese)

We can use `utils/build_unicode_table.pl src/fs/language/locale/*.po` to locate all needed characters, but still need to cross-check against the fonts

**Comment by howard0su** [comment]
the font need regenerate for JA. We didn't includes the characters for Japanese.

**Comment by howard0su** [comment]
we need a free Japanese font to regenerate bfd files.
