### ISSUE TITLE
Devo8 dev build is broken

### ISSUE THREAD

**Issue by howard0su** [DeviationTX/deviation#634]
It is over ROM size limit:
 region `rom' overflowed by 740 bytes

My suggestions:
1. Don't enable printf by default in dev build
2. Enable debuglog in dev build
3. developer can use 'make CFLAGS_clock = -DENABLE_DEBUG_PRINT' to enable printf per file (the feature I introduced recently.)

Thoughts?

**Comment by PhracturedBlue** [comment]
Not really my favorite answer.  A lot of the upcoming patches should address this (LTO and/ or your model configuration).  So this issue should resolve itself pretty soon.  It seems like a lot of work to need to manually enable debug in that way.  possibly if we had classes of debug (protocol, gui, interrupt, buttons, etc) that we could choose to enable or not, it'd be better, but that classification is also a lot of work.

**Comment by howard0su** [comment]
LTO seems to solve the problem.
ROM: 0x08004000 - 0x0803debc = 231.68kB
RAM: 0x20000000 - 0x200067f8 =  25.99kB
