### ISSUE TITLE
deviationtx.com down

### ISSUE THREAD

**Issue by TheRealMoeder** [DeviationTX/deviation#683]
"This Account has been suspended."

**Comment by PhracturedBlue** [comment]
working on it

**Comment by TheRealMoeder** [comment]
Here we go again

**Comment by PhracturedBlue** [comment]
I am aware.  Support is not being responsive.  I probably need to find a better hosting service, but don't have the bandwidth to do so right now

**Comment by TheRealMoeder** [comment]
Issue solved, thanks @PhracturedBlue for once again quick response

**Comment by TheRealMoeder** [comment]
Once again...

**Comment by goebish** [comment]
Working fine here

**Comment by PhracturedBlue** [comment]
works fine here too.  I changed the DNS entries, but that was 2 days ago and shouldn't affect anyone now.  We also have new firewall rules, but they shouldn't affect traffic directly to the website.

The return of nslookup and whatever error you browser returns may be helpful.

**Comment by gdenton61** [comment]
http://www.deviationtx.com/ returns "404 Not Found" for me.
https works.

**Comment by PhracturedBlue** [comment]
Thanks.  The redirect from www.deviationtx.com to deviationtx.com wasn't setup properly.  It should be working now.  Let me know if you still see issues.
