### ISSUE TITLE
The Docker container does not have a separate Devo TX build option that needs help!

### ISSUE THREAD

**Issue by wind1007** [DeviationTX/deviation#778]
Today, the Deviation build environment was downloaded again. Now the Docker container is started, Deviation Ware Builder 0.9.5. There is no separate DEVO TX build option for the container build selection. There are only(drivers) and(TX) in the Transmitter builde option, no single(Devoxx), and there are also many Emulators for Windows options.

**Comment by howard0su** [comment]
@TheRealMoeder  did you fix this?

**Comment by TheRealMoeder** [comment]
Already fixed in DeviationTX/deviation-docker#6
Will need further enhancement to support radiolink and opentx targets once they are ready.
