### ISSUE TITLE
[TODO] better and cleaner scanner support

### ISSUE THREAD

**Issue by howard0su** [DeviationTX/deviation#810]
couple of things we can do improve here:
1. Clean up code and move the code out of the UI logic
2. Support devo7e? (PR #568 )
3. Use CC2500 if possible, fallback to CYRF: (@TheRealMoeder )
https://www.vincentgijsen.nl/post/doing-some-rf-spectrum-analyser-stuff/

**Comment by TheRealMoeder** [comment]
Already working on this.

**Comment by TheRealMoeder** [comment]
Related PRs: #813

**Comment by TheRealMoeder** [comment]
1. and 2. are finished. 3 will be addressed in seperate PR.
