### ISSUE TITLE
Devo 7e 3x2 switches not working

### ISSUE THREAD

**Issue by daniel-snowsurf** [DeviationTX/deviation#838]
With current version nightly & build from master the 3x2 switches are not working properly. Both switches SWA & SWB read wrong values:
0 position gets 0
1 position gets 0
2 position gets 1
Going back to Nov 2017 versions gets it working fine again. Details posted in:
[https://www.deviationtx.com/forum/6-general-discussions/8361-devo-7e-3x2-switches-not-working-anymore#73614](url)

**Comment by PhracturedBlue** [comment]
Thanks for the report.  I've confirmed that while the 3x2 switches work fine with the devo7e-256, they do not work properly with the devo7e build.  I'm looking at it

**Comment by vidzo** [comment]
I too am having the same issue using Moeders fork

**Comment by TheRealMoeder** [comment]
Is this relaxed?
https://www.deviationtx.com/forum/stock-firmware-help/8366-t8sg-aux-5-not-working-after-fw-upgrade

**Comment by PhracturedBlue** [comment]
I don't think so.  Likely recalibration is all that is needed for that issue.

**Comment by vidzo** [comment]
Thanks. Switch is fixed, however Throttle trim TRIMLV- does not work. Furthermore RUDDER stick fails to work after adding 3x2 define in hardware.ini.

**Comment by PhracturedBlue** [comment]
I can reproduce the trimLV- not working and I'll fix.  I cannot reproduce your rudder issue though.  My rudder works fine.  Try recalibration?

**Comment by vidzo** [comment]
As movement isn't recognised, it won't calibrate that axis. If I remove the 3x2 define, channel/stick repsonds as standard. I'm using Moeders fork so not sure if there are significant differences

**Comment by PhracturedBlue** [comment]
I cannot help you with Moeder's fork.

**Comment by vidzo** [comment]
Ok, thanks anyway. I'll have to wait until voice alerts and editor/layout editor make it to the nightlies for Devo 7E

**Comment by TheRealMoeder** [comment]
My feature branch doesn't touch this, but I can merge in current nightly, if it helps. Though I doubt this issue is related.

**Comment by vidzo** [comment]
I'm not sure. I'll try again compiling with the changes, I don't see how it could break rudder channel but I'm no coder.

**Comment by daniel-snowsurf** [comment]
Thanks for the fix. Just build the Devo 7e and 3x2 switches work fine. As already said LV trim is not working. I use it as a switch, it's always ON.

**Comment by vidzo** [comment]
@Moeder, do you think you'll be able to look at the Rudder channel issue with the applied fixes to your master/voice_diet fork?

**Comment by TheRealMoeder** [comment]
Do you see the rudder channel issue in current master?

**Comment by vidzo** [comment]
It appears that I overlooked the master. It's all working fine, checked out to master, applied code and no issues with rudder. Sorry for not checking. So the issue is with voice_diet I think. No worries, I'll use master and probably end up making U7e. Thanks for your time and work Moeder and PB

**Comment by TheRealMoeder** [comment]
I've updated voice_diet2 to current master...please report if the issue persists.

**Comment by vidzo** [comment]
Another user has reported the same problem of being unable to use rudder once a calibration has taken place

**Comment by TheRealMoeder** [comment]
I thought you didn't experience it anymore in master

**Comment by vidzo** [comment]
I hadn't tested properly. I had flashed it, checked if 3x2 switch was working but didn't do a calibration of the sticks. Been involved with other projects so didn't check until the previous night, hence why I came back to GitHub to check

**Comment by TheRealMoeder** [comment]
Rudder calibration issue on devo7e should be fixed with #862
