### ISSUE TITLE
Devo 7e: Calibration makes tx stick unusable

### ISSUE THREAD

**Issue by joschtec** [DeviationTX/deviation#850]
No input on left stick (Yaw) after done CALIBRATION
Devo7e with extra  extra-switches= 3x2

found in tx.ini :

[calibrate4]
  max=0
  min=0
  zero=0

**Comment by vidzo** [comment]
This. I am having the same issue on, had it for weeks

**Comment by TheRealMoeder** [comment]
Should be fixed with #862
