### ISSUE TITLE
Jumper T8SG V2 Plus: Thrust trim switch not working upwards

### ISSUE THREAD

**Issue by JoeDante** [DeviationTX/deviation#852]
On Jumper T8SG V2 Plus:n thrust trim switch is not working upwards. Down is OK.

**Comment by TheRealMoeder** [comment]
I can confirm, although in reverse: upwards works fine, downwards does not. Same TX.

**Comment by TheRealMoeder** [comment]
I just noticed I had a very special test build on my t8sg v2+, although it did exhibit this behavior! Cannot reproduce it with the current nightly though. Can you tell us the which build you have showing the issue? You can check the build id in the "About Deviation" Page in the main menu

**Comment by hexfet** [comment]
Also tested latest nightly and no issue found.
