### ISSUE TITLE
Jumper T8SG Plus debug-t8sg_v2_plus-v5.0.0-a55485f

### ISSUE THREAD

**Issue by CarlosRibes** [DeviationTX/deviation#867]
Please help

**Comment by CarlosRibes** [comment]
1.- I get the message "External voice currently not avalaible". What does it mean? How does the voice work?
2.- In the configuration of the telemetry after "Temperature" and "Length" the "Alert interval" is set. What does that alert warn about?
3.- I do not know how to configure the alert for loss of the link with the drone.

**Comment by hexfet** [comment]
The deviation forum is more appropriate for questions like these.
The wiki linked there has information on installing and configuring voice support.
Usually the receiver will send RSSI or a link quality indicator that can be used for alarming on the radio link.
