### ISSUE TITLE
Turn off power doesn't need to hold power button

### ISSUE THREAD

**Issue by ariefadha** [DeviationTX/deviation#883]
i hop this is the right place.

deviation-t8sg_v2_plus-v5.0.0-28ce50f 

here is the bug that i found
1. to turn off the TX its no longer need to hold the button.
2. timer stop-prop and cntdn-prop, start automatically and "control switch" not effected the timer.
3. left button reset the timer.

**Comment by Tygrys-1** [comment]
1) Confirm, it should be longer.
3) It is the feature, not a bug. Left button is for reset and right for start/stop if no other switches are assigned for these functions in the timer configuration.

**Comment by TheRealMoeder** [comment]
I don't quite understand the second issue

**Comment by ariefadha** [comment]
for the second issue : if i fly "plane" or "drone" i want the cntd-prop to count when only the props are spinning, or have a switch that can pause the cntd-prop-timer. how i do that?

**Comment by Tygrys-1** [comment]
If you use a 3-pos switch, in the middle position the proportional counter will stop.
For throttle-dependant see #887 - this will measure the time proportional to the THR value. 
You may also use the normal stopwatch timer with the switch set to THR - it will start count at normal speed for the throttle value >-90

**Comment by vladislavy** [comment]
Fixed
