### ISSUE TITLE
Devo 12e screen flip 

### ISSUE THREAD

**Issue by SirDomsen** [DeviationTX/deviation#982]
Screen flipped and mirrored on latest branch. Did test a few commits earlier, all have the same problem.
Pictures of issue see here:
http://gofile.me/3SzTG/r6wCZGNer
http://gofile.me/3SzTG/UOK2Z8fBB

**Comment by vladislavy** [comment]
Try next nightly build.

**Comment by SirDomsen** [comment]
thank you very much
